language: node_js
node_js:
addons:
  firefox: "45.2.0esr"
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm prune
cache:
  directories:
    - node_modules
notifications:
  email:
    on_success: change
    on_failure: always
