language: node_js
node_js:
addons:
  firefox: "45.2.0"
before_script:
  - npm prune
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
cache:
  directories:
  - node_modules
notifications:
  email:
    on_success: change
    on_failure: always
